version: '3'

services:
  nginx:
    container_name: currency-exchange-nginx
    labels:
      ru.grachevko.dhu: exchange.currency
    networks:
      currency-exchange:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
  php:
    container_name: currency-exchange-php
    labels:
      ru.grachevko.dhu: currency-exchange-php
    networks:
      currency-exchange:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../../projects/currency-exchange:/var/www:rw
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        - UID=$UID
        - SITE_URL=exchange.currency
    restart: unless-stopped
networks:
  currency-exchange:
    external:
      name: currency-exchange
